---
# name: jam82.firewalld
# file: tasks/main.yml

- name: "Ensure firewalld is installed"
  become: true
  ansible.builtin.package:
    name: firewalld
    state: present

- name: "Ensure directory for custom definitions exist"
  become: true
  ansible.builtin.file:
    path: "/etc/firewalld/{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - ipsets
    - policies
    - services
    - zones

- name: "Generate firewalld configuration file"
  become: true
  ansible.builtin.template:
    src: firewalld.conf.j2
    dest: /etc/firewalld/firewalld.conf
    mode: '0640'
  notify: Reload firewalld

- name: "Create custom ipsets"
  become: true
  ansible.builtin.template:
    src: ipset.xml.j2
    dest: "/etc/firewalld/ipsets/{{ item.name }}.xml"
    mode: '0640'
  loop: "{{ firewalld_ipsets }}"
  notify: Reload firewalld
  when: firewalld_ipsets is defined

- name: "Create custom services"
  become: true
  ansible.builtin.template:
    src: service.xml.j2
    dest: "/etc/firewalld/services/{{ item.name }}.xml"
    mode: '0640'
  loop: "{{ firewalld_services }}"
  notify: Reload firewalld
  when: firewalld_services is defined

- name: "Create custom policies"
  become: true
  ansible.builtin.template:
    src: policy.xml.j2
    dest: "/etc/firewalld/policies/{{ item.name }}.xml"
    mode: '0640'
  loop: "{{ firewalld_policies }}"
  notify: Reload firewalld
  when: firewalld_policies is defined

- name: "Generate zone definitions"
  become: true
  ansible.builtin.template:
    src: zone.xml.j2
    dest: "/etc/firewalld/zones/{{ item.name }}.xml"
    mode: '0640'
  loop: "{{ firewalld_zones }}"
  notify: Reload firewalld
  when: firewalld_zones is defined

- name: "Ensure firewalld is started and enabled"
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: "Manage direct rules"
  become: true
  ansible.builtin.command:
    cmd: "firewall-cmd --permanent --direct --add-rule {{ item }}"
  loop: "{{ firewalld_direct_rules }}"
  when: firewalld_direct_rules | length > 0
  changed_when: false
  notify: Reload firewalld
