---
# name: jam82.firewalld
# file: tasks/zone.yml

- name: "Manage ICMP Blocks"
  become: true
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    icmp_block_inversion: "{{ item.icmp_block_inversion }}"
    icmp_block: "{{ icmp_block }}"
    state: "{{ item.state }}"
    permanent: true
    immediate: true
  loop: "{{ item.icmp_blocks }}"
  loop_control:
    loop_var: icmp_block
  when: "'icmp_blocks' in item"

- name: "Add services to zones"
  become: true
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    service: "{{ service }}"
    state: "{{ item.state }}"
    permanent: true
    immediate: true
  loop: "{{ item.services }}"
  loop_control:
    loop_var: service
  when: "'services' in item"

- name: "Add interfaces to zones"
  become: true
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    interface: "{{ interface }}"
    state: "{{ item.state }}"
    permanent: true
    immediate: true
  loop: "{{ item.interfaces }}"
  loop_control:
    loop_var: interface
  when: "'interfaces' in item"

- name: "Add source addresses to zones"
  become: true
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    source: "{{ source_address }}"
    state: "{{ item.state }}"
    permanent: true
    immediate: true
  loop: "{{ item.source_addresses }}"
  loop_control:
    loop_var: source_address
  when: "'source_addresses' in item"
